releasetools: fix out of range issue for incremental OTA
  File "common.py", line 1497, in __init__
    b.Compute(self.path)
  File "blockimgdiff.py", line 317, in Compute
    self.FindVertexSequence()
  File "blockimgdiff.py", line 1050, in FindVertexSequence
    u = heapq.heappop(heap)
        ^^^^^^^^^^^^^^^^^^^
IndexError: index out of range

Change-Id: Ie9ce34892caf8e0d52c5f0ed44a3ea918a08045c
(cherry picked from commit 6034234d9c7cebdd0217263a7c500f7499684268)
(cherry picked from commit c7ed9ed9c792c56f6c01797a840512d96704f93f)